CREATE TABLE `orderlist` (
  `orderid` int NOT NULL AUTO_INCREMENT,
  `userid` int NOT NULL,
  `wxid` int NOT NULL,
  `product_trade` varchar(64) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'product id',
  `paytype` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '支付渠道 0=未标记 1=alipay 2=wxpayv2 3=wxpayv3 4=weixinxcx',
  `openid` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `wxorder` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'out order',
  `storeorder` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'in order',
  `totalnum` int unsigned NOT NULL,
  `addtime` int unsigned NOT NULL,
  `paytime` int unsigned NOT NULL,
  `payip` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `username` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `address` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `mobile` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `payprice` int unsigned NOT NULL COMMENT 'cents',
  `shipprice` int unsigned NOT NULL COMMENT 'cents',
  `isrefund` tinyint NOT NULL,
  `isship` tinyint NOT NULL,
  `isfinsh` tinyint NOT NULL,
  `isremove` tinyint unsigned NOT NULL COMMENT '用户删除，后台不删除',
  `refundnum` int unsigned NOT NULL,
  `paytitle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `liuyan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `excomany` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '快递公司',
  `exnumber` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '快递单号',
  `expaddtime` int unsigned NOT NULL COMMENT '快递添加时间',
  `goodsid` int unsigned NOT NULL COMMENT 'product id',
  `status` int NOT NULL COMMENT '流转状态',
  `jifen` int unsigned NOT NULL,
  PRIMARY KEY (`orderid`),
  UNIQUE KEY `uk_wxorder` (`wxorder`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单表'