/*build this file time Tue, 20 Dec 2022 11:40:56 GMT*/

#include "cms/include/Article.h"
#include "cms/include/Testa.h"
#include "cms/include/Testb.h"
#include "cms/include/Department.h"
#include "cms/include/Topic.h"
#include "cms/include/Siteinfo.h"
#include "cms/include/Logininfo.h"
#include "Fortune.h"
#include "World.h"
#include "cms/include/Brand.h"
#include "cms/include/Blogcatalog.h"
#include "cms/include/Catalogue.h"
#include "cms/include/Homeblock.h"
#include "cms/include/Product.h"
#include "cms/include/Superadmin.h"
#include "cms/include/Sysperms.h"
#include "cms/include/Sysrole.h"
#include "cms/include/Sysuser.h"