/*build this file time Sat, 26 Apr 2025 14:46:47 GMT*/

#include "Fortune.h"
#include "World.h"
#include "cms/include/Article.h"
#include "cms/include/Blogcatalog.h"
#include "cms/include/Brand.h"
#include "cms/include/Catalogue.h"
#include "cms/include/Department.h"
#include "cms/include/Homeblock.h"
#include "cms/include/Logininfo.h"
#include "cms/include/Product.h"
#include "cms/include/Productparam.h"
#include "cms/include/Siteinfo.h"
#include "cms/include/Superadmin.h"
#include "cms/include/Sysperms.h"
#include "cms/include/Sysrole.h"
#include "cms/include/Sysroleperms.h"
#include "cms/include/Sysuser.h"
#include "cms/include/Testa.h"
#include "cms/include/Testb.h"
#include "cms/include/Topic.h"
#include "cms/include/Xmeet.h"
#include "cms/include/Xproject.h"
#include "cms/include/Xtalk.h"
#include "cms/include/Xtask.h"
#include "cms/include/Sitelog.h"
#include "cms/include/Topicset.h"