CREATE TABLE `xproject` (
  `xpjid` int unsigned NOT NULL AUTO_INCREMENT,
  `userid` int unsigned NOT NULL,
  `prexpjid` int unsigned NOT NULL,
  `dpid` int unsigned NOT NULL,
  `grouptype` int unsigned NOT NULL,
  `title` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `adminuserid` int unsigned NOT NULL,
  `regdate` int unsigned NOT NULL,
  `begindate` int unsigned NOT NULL,
  `expiredate` int unsigned NOT NULL,
  `isopen` tinyint NOT NULL,
  `clientid` int unsigned NOT NULL,
  `totalnum` int unsigned NOT NULL,
  `referdocverion` int unsigned NOT NULL,
  `xtheme` int unsigned NOT NULL,
  `xlogo` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `introduce` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `giturl` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `gitname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `gitpwd` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `xcolor` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `fupan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `totalvalue` double NOT NULL,
  `expectday` float NOT NULL,
  `realday` float NOT NULL,
  PRIMARY KEY (`xpjid`),
  KEY `userid` (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='项目表'