CREATE TABLE `xtask` (
  `xtaskid` int unsigned NOT NULL AUTO_INCREMENT,
  `userid` int unsigned NOT NULL,
  `xpjid` int unsigned NOT NULL,
  `adminid` int unsigned NOT NULL,
  `parentid` int unsigned NOT NULL,
  `begindate` int unsigned NOT NULL,
  `enddate` int unsigned NOT NULL,
  `expectbegindate` int unsigned NOT NULL,
  `expectenddate` int unsigned NOT NULL,
  `milestone` int unsigned NOT NULL,
  `subxpjid` int unsigned NOT NULL,
  `depxtaskid` int unsigned NOT NULL,
  `referdocid` int unsigned NOT NULL,
  `isfinish` tinyint unsigned NOT NULL,
  `updatedate` int unsigned NOT NULL,
  `finishdate` int unsigned NOT NULL,
  `iscore` int unsigned NOT NULL,
  `xvalue` double NOT NULL,
  `expectday` float NOT NULL,
  `realday` float NOT NULL,
  `pricevalue` float NOT NULL,
  `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `introduce` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `xlogo` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `xcolor` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `pullurl` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `pulltitle` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `pullauthor` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `itemnote` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`xtaskid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='项目任务表'