[info]
acme_path  = /Users/hzq/paozhu/acme ;项目目录下acme 目录，存放申请中间文件
cert_path  = /usr/local/etc/paozhu ;域名证书存放
email      = ;必须设置邮箱才能生效，Email must be set to take effect server.conf 相应的域名下 acme_auto=1 才能自动 
days_remain= 10 ;剩余多少天才更新SSL证书

[zerossl]
server_url = https://acme.zerossl.com/v2/DV90
eab_api    = https://api.zerossl.com/acme/eab-credentials-email
eab_kid	=
eab_hmac_key =
email      = 
user_name  =
user_pwd   =