[default]
threadmax                  = 1024
threadmin                  = 5
httpport                   = 80
httpsport                  = 443
bmcport                    = 7755 ;Baseboard Management Controller
cothreadnum                = 8 ;Coroutines run on thread num

http2_enable               = 1
debug_enable               = 1
deamon_enable              = 0
ip6_listen_enable          = 1
mainhost                   = www.hggq.com
certificate_chain_file     = www.hggq.com.pem
private_key_file           = www.hggq.com.key
tmp_dh_file                = dh4096.pem
chain_crt_file             = www.hggq.com.crt
reboot_password            = e10adc3949ba59abbe56e057f20f883e ;md5(md5("123456")+"rand_char"+md5("123456"))
reboot_cron                = d180h5 ;MDSW+Hhours reboot process M month D day S season (1 4 7 10) W week
clean_cron                 = m5t600 ;5-minute interval clean 600 seconds ago inactive connection
links_restart_process      = n9998877ts1te5 ;More than 15000 connections, restart the process from 1:00 am to 5:00 am
session_type               = 1 ;session save type 0.file 1.memory 2.redis 3.memcache 4.reserve
static_file_compress_cache = 1 ;1 enable, Cache static file compress(gzip,br) content to cache directory

rate_limit_status          = 0 ; 1 enable Traffic limiting
rate_limit_new_wait_num    = 300 ;level 1, The waiting time for the start of 300 connections is randomly between down and up
rate_limit_accept_wait_num = 600 ;level 2, Start limiting accept reception, need sleep time
rate_limit_accept_time     = 250 ;accept sleep milliseconds, max 1500

modelspath                 = ./models
serverpath                 = ./
viewpath                   = ./view
viewsopath                 = ./module/view

controlpath                = ./controller
controlsopath              = ./module/controller

temppath                   = ./temp
logpath                    = ./log
wwwpath                    = ./www/default
pluginspath                = ./plugins
libspath                   = ./libs
directorylist              = 1
index                      = index.html
;usehtmlcache=1
;usehtmlcachetime=3600

acme_auto                  = 0 ;acme automatically applies for SSL certificates, 1 自动更新SSL证书
acme_every_day             = 7 ;What time does acme run every day, 每天几点运行一次，如果有证书需要就更新
acme_every_num             = 5 ;How many domain names are processed at a time, 每次处理几个域名
ocsp_intv_time             = 14400 ;OCSP update interval second, OCSP 更新时间间隔 至少4小时

staticfile_cache_num       = 0 ;0 not cache, min 10 begin
rewrite_404                = 0 ;1 file 2 action url path
rewrite_404_action         = index.html
method_pre                 = 
method_after               = 
show_visitinfo             = 0
upload_max_size            = 16777216
siteid                     = 1
groupid                    = 0
alias_domain               = 
init_func                  = 

[www.hggq.com]
wwwpath                    = ./www/default
http2_enable               = 1
acme_auto                  = 0
;rewrite_404=1
;rewrite_404_action=index.html|psy/index.html|exam/index.html
;controlsopath=./controller
static_pre                 = downloadfileauth|upload
method_pre                 =  ;api/dev/hostcors
method_after               = 
isuse_php                  = 0
rewrite_php                = ./www/mpdftest|index.php
fastcgi_host               = 127.0.0.1 ;/run/php/php8.1-fpm.sock
fastcgi_port               = 9000
upload_max_size            = 16777216
siteid                     = 1
groupid                    = 0
alias_domain               = 
init_func                  = 
