[default]
port           = 80 ;http point
wwwpath        = /www/paozhu/www/default ;项目目录

siteid         = 1
;domains begin
;the second domain name

[www.abc.com]
;域名web的根目录

wwwpath        = /www/paozhu/www/abc ;域名目录
websocket_path = /www/paozhu/www/abc ;websocket目录
siteid         = 2
themes         = flash
